name: Build and publish NuGet package

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Environment
      run: echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV

    - name: Build
      run: |
        dotnet build --configuration Release /p:Version=${{ env.RELEASE_VERSION }}
        dotnet pack --configuration Release /p:Version=${{ env.RELEASE_VERSION }}

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ github.event.workflow_run.head_commit.message }}
        files: bin/Release/RGBradCSharpTest.${{ env.RELEASE_VERSION }}.nupkg

    - name: Push to GitHub NuGet registry
      run: |
        dotnet nuget push \
          bin/Release/RGBradCSharpTest.${{ env.RELEASE_VERSION }}.nupkg \
          --source https://nuget.pkg.github.com/brad-rocketgate/index.json \
          --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Push to NuGet.org registry
      run: |
        dotnet nuget push \
          bin/Release/RGBradCSharpTest.${{ env.RELEASE_VERSION }}.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ secrets.NUGET_TOKEN }}
